version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: "monday"
      time: "05:06"
      timezone: "Europe/Stockholm"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: "monday"
      time: "05:06"
      timezone: "Europe/Stockholm"
    groups:
      go:
        patterns:
          - "*"  # Include all dependencies in one PR
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: gomod
    directory: .sage
    schedule:
      interval: weekly
      day: "monday"
      time: "05:06"
      timezone: "Europe/Stockholm"
